server:
  port: 8088
spring:
  application:
    name: finx-auth-service
  zipkin:
    base-url: http://192.168.1.232:9411/
  eureka:
    client:
      service-url:
      defaultZone: http://192.168.1.232:8761/eureka
      register-with-eureka: true
logging:
  level:
    root: INFO