server:
  port: 8089
spring:
  application:
    name: finx-admin-service
  zipkin:
    base-url: http://192.168.1.232:9411/
  eureka:
    client:
      service-url:
      defaultZone: http://192.168.1.232:8761/eureka
      register-with-eureka: true
  datasource:
    url: jdbc:mysql://192.168.1.29:3306/finx_admin_v1_03?zeroDateTimeBehavior=convertToNull
    username: coreuser
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    root: ERROR
  
